package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

// HandleGreeting processes HTTP requests to generate greetings in different languages.
//
// @Summary Generate a greeting message
// @Description Returns a greeting message in the requested language.
// @Tags greeting
// @Accept  json
// @Produce  json
// @Param name query string false "Name to greet" default(World)
// @Param lang query string false "Language code (en, es, fr)" default(en)
// @Success 200 {object} GreetingResponse
// @Failure 500 {string} string "Internal Server Error"
// @Router /greet [get]
func HandleGreeting() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Parse query parameters
		name := r.URL.Query().Get("name")
		lang := r.URL.Query().Get("lang")

		// Default values
		if name == "" {
			name = "World"
		}
		if lang == "" {
			lang = "en"
		}

		// Determine greeting
		var greeting string
		switch strings.ToLower(lang) {
		case "es":
			greeting = "¡Hola"
		case "fr":
			greeting = "Bonjour"
		default:
			greeting = "Hello"
		}

		message := fmt.Sprintf("%s %s!", greeting, name)

		// Update metrics
		totalGreetingsCounter.Inc()
		greetingsByLangCounter.WithLabelValues(lang).Inc()

		// Construct response
		response := GreetingResponse{
			Message:   message,
			Language:  lang,
			Timestamp: time.Now().UTC(),
		}

		// Encode response as JSON
		if err := encode(w, r, http.StatusOK, response); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	})
}

// GreetingResponse represents the JSON response structure
type GreetingResponse struct {
	Message   string    `json:"message"`
	Language  string    `json:"language"`
	Timestamp time.Time `json:"timestamp"`
}

// Metrics
var (
	totalGreetingsCounter = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "total_greetings",
			Help: "Total number of greetings generated",
		},
	)
	greetingsByLangCounter = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "greetings_by_language",
			Help: "Number of greetings generated by language",
		},
		[]string{"language"},
	)
)

// Register metrics with Prometheus
func init() {
	prometheus.MustRegister(totalGreetingsCounter, greetingsByLangCounter)
}

// https://grafana.com/blog/2024/02/09/how-i-write-http-services-in-go-after-13-years/#handle-decodingencoding-in-one-place
func encode[T any](w http.ResponseWriter, r *http.Request, status int, v T) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if err := json.NewEncoder(w).Encode(v); err != nil {
		return fmt.Errorf("encode json: %w", err)
	}
	return nil
}
