apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: helloworld-pipeline
description: helloworld application delivery pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: 
   - dev
 - targetId: staging
   profiles: 
   - staging
#  - targetId: prod
#    profiles: []

