name: Build and Push Go HTTP Docker Image

# Only run on pushes to main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/top-chain-475617-p7/test-repo/go-http-server:latest -f deploy/Dockerfile .

    - name: Push Docker image
      run: |
        docker push us-central1-docker.pkg.dev/top-chain-475617-p7/test-repo/go-http-server:latest

    - name: Deploy with Cloud Deploy
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: top-chain-475617-p7
        service_account_key: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
        gcloud deploy releases create "app-release-${{ github.sha }}" \
          --delivery-pipeline=helloworld-pipeline \
          --region=us-central1 \
          --skaffold-file=deploy/skaffold.yaml